---
  - name: FileBeat install playbook
    hosts: webservers
    become: true
    tasks:

    - name: Download elastic deb file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    - name: Install the dpkg file
      command: dpkg -i filebeat-7.4.0-amd64.deb

    - name: Copy filebeat config file to VM
      copy:
        src: /etc/ansible/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: enable and configure module
      command: filebeat modules enable system

    - name: setup filebeat
      command: filebeat setup

    - name: start filebeat service
      command: service filebeat start 

    - name: enable service filebeat on restart
      systemd:
        name: filebeat
        enabled: yes
